package com.wisebox.gyb;

public class TrainInfo {
	public String m_TrainNo;
	public String m_TrainName;
	public String m_CourseNo;
	public String m_CourseName;
	public String m_CourseType;
	public String m_ScoreType;
	public String m_IsOnBoardTrain = "";
	public String m_TeacherNo = "";
	public String m_TeacherName = "";
	public String m_Location = "";
	public String m_TotalStudentsNo = "";
	public String m_AttendStudentsNo = "";
	public String m_Note = "";
	public String m_State = "";
	public String m_DeptNo = "";
	public String m_DeptName = "";
	public String m_CREATER = "";
	public String m_CREATEDATE = "";
	public String m_MODIFIERID = "";
	public String m_MODIFYDATE = "";
	public String m_String1 = "";
	public String m_String2 = "";
	public String m_String3 = "";
	public String m_String4 = "";
	public String m_String5 = "";
	public String m_String6 = "";
	public String m_String7 = "";
	public String m_String8 = "";
	public String m_String9 = "";
	public String m_String10 = "";
	public String m_String11 = "";
	public String m_String12 = "";
	public String m_String13 = "";
	public String m_String14 = "";
	public String m_String15 = "";
	public String m_String16 = "";
	public String m_String17 = "";
	public String m_String18 = "";
	public String m_String19 = "";
	public String m_String20 = "";

	public static TrainInfo Copy(TrainInfo to) {
		TrainInfo tn = new TrainInfo();
		tn.m_TrainNo = to.m_TrainNo;
		tn.m_TrainName = to.m_TrainName;
		tn.m_CourseNo = to.m_CourseNo;
		tn.m_CourseName = to.m_CourseName;
		tn.m_CourseType = to.m_CourseType;
		tn.m_ScoreType = to.m_ScoreType;
		tn.m_IsOnBoardTrain = to.m_IsOnBoardTrain;
		tn.m_TeacherNo = to.m_TeacherNo;
		tn.m_CREATEDATE = to.m_CREATEDATE;
		tn.m_CREATER = to.m_CREATER;
		tn.m_TeacherName = to.m_TeacherName;
		tn.m_Location = to.m_Location;
		tn.m_TotalStudentsNo = to.m_TotalStudentsNo;
		tn.m_AttendStudentsNo = to.m_AttendStudentsNo;
		tn.m_DeptName = to.m_DeptName;
		tn.m_DeptNo = to.m_DeptNo;
		tn.m_MODIFIERID = to.m_MODIFIERID;
		tn.m_MODIFYDATE = to.m_MODIFYDATE;
		tn.m_Note = to.m_Note;
		tn.m_State = to.m_State;
		tn.m_String1 = to.m_String1;
		tn.m_String2 = to.m_String2;
		tn.m_String3 = to.m_String3;
		tn.m_String4 = to.m_String4;
		tn.m_String5 = to.m_String5;
		tn.m_String6 = to.m_String6;
		tn.m_String7 = to.m_String7;
		tn.m_String8 = to.m_String8;
		tn.m_String9 = to.m_String9;
		tn.m_String10 = to.m_String10;
		tn.m_String11 = to.m_String11;
		tn.m_String12 = to.m_String12;
		tn.m_String13 = to.m_String13;
		tn.m_String14 = to.m_String14;
		tn.m_String15 = to.m_String15;
		tn.m_String16 = to.m_String16;
		tn.m_String17 = to.m_String17;
		tn.m_String18 = to.m_String18;
		tn.m_String19 = to.m_String19;
		tn.m_String20 = to.m_String20;

		return tn;
	}
}
